import os

env = Environment( # type: ignore
    tools = ['g++', 'gcc', 'gnulink'],  
    CXX = 'g++',
    CC = 'gcc',
    CXXFLAGS = ['-std=c++20', '-O3', '-march=native', '-mtune=native', '-Wall', '-Wextra', '-Wno-unused-parameter'],
    CCFLAGS=["-w"],
    LINKFLAGS=['-static', '-static-libgcc', '-static-libstdc++', '-s'],
    ENV = {
        'PATH': r'C:\\msys64\\mingw64\\bin;' + os.environ['PATH'],
        'TEMP': os.environ.get('TEMP', 'G:\\temp'), 
        'TMP':  os.environ.get('TMP',  'G:\\temp')
    }
)

sources = Glob("./*.cpp") #type: ignore
sources += Glob("./**/*.cpp") #type: ignore
sources += Glob("./**/**/*.cpp") #type: ignore
sources += Glob("../chess/**/*.cpp") #type: ignore

excluded = ["uci_engine_communicator"]
sources = [f for f in sources if not any(ex in str(f) for ex in excluded)]

env.Program(target="engine.exe", source=sources)